const KEY='w2wTraderState';
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function setState(p){const s=Object.assign({},state(),p);localStorage.setItem(KEY,JSON.stringify(s));return s}
document.addEventListener('DOMContentLoaded',function(){
var save=document.getElementById('saveMaterial');
if(save)save.onclick=function(){var inputs=document.querySelectorAll('input'),fingerprint={name:inputs[0]?inputs[0].value:'Steel Slag',quantity:inputs[1]?inputs[1].value:'240 MT',location:inputs[2]?inputs[2].value:'Chennai',availability:document.querySelector('select')?document.querySelector('select').value:'Available now',quality:document.querySelector('textarea')?document.querySelector('textarea').value:'High grade'};setState({fingerprint:fingerprint});var n=document.getElementById('saveNotice');if(n)n.textContent='Material fingerprint saved. AI matching, pathway and passport modules can now use this record.'};
var ms=document.getElementById('matchSummary');if(ms){var f=state().fingerprint;ms.textContent=(f?f.name:'Steel Slag')+' → 3 pathway classes discovered'}
document.querySelectorAll('.pathwayChoice').forEach(function(b){b.onclick=function(){setState({selectedPath:b.dataset.path,requestStage:'Exchange Request'});var n=document.getElementById('pathChoiceNotice');if(n)n.textContent=b.dataset.path+' selected. Go to Requests to begin the exchange lifecycle.'}});
var adv=document.getElementById('advanceRequest');if(adv)adv.onclick=function(){var stages=['Exchange Request','Negotiation','Verification','Agreement','Transaction','Impact Record'],s=state(),i=Math.max(0,stages.indexOf(s.requestStage||'Exchange Request'));i=Math.min(i+1,stages.length-1);setState({requestStage:stages[i]});var e=document.getElementById('requestStage');if(e)e.textContent=stages[i];var n=document.getElementById('requestNotice');if(n)n.textContent='Request moved to '+stages[i]+'.'};
var stage=document.getElementById('requestStage');if(stage&&state().requestStage)stage.textContent=state().requestStage;
var pm=document.getElementById('passportMaterial'),pc=document.getElementById('passportComposition'),pe=document.getElementById('passportExchange');if(pm){var f2=state().fingerprint||{};pm.textContent=f2.name||'Steel Slag — High Grade';if(pc)pc.textContent=f2.quality||'High grade';if(pe)pe.textContent=state().requestStage||'Pending'}
var calc=document.getElementById('calculateImpact');if(calc)calc.onclick=function(){var q=Number(document.getElementById('impactQty').value||0),r=Number(document.getElementById('impactRate').value||0),d=Math.round(q*r/100),out=document.getElementById('impactResult');out.textContent='Estimated diversion: '+d.toLocaleString()+' kg. Prototype estimate for decision support, not a certified LCA.';setState({impact:{quantity:q,rate:r,diverted:d}})}
});